on:
  pull_request:
    types: [labeled, opened, synchronize]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.4'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build project
        run: CI=false npm run build

      - name: Start server
        run: |
          npm install -g serve
          serve -s build -l 3000 &
          sleep 5

      - name: Run Cypress tests
        run: |
          npm start &
          npm run cypress:run

  auto-merge:
    needs: e2e-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install gh -y

      - name: Auto merge if checks pass
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth setup-git
          gh pr review ${{ github.event.pull_request.number }} --approve
          gh pr merge ${{ github.event.pull_request.number }} --merge
